# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Swift笔记' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 3.2.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'Alamofire', '~> 4.4.0'
pod 'YYModel', '~> 1.0.4'
 # Pods for Swift笔记

end
